const aslAlphabet = [
    { letter: "A", image: "images/A.png", description: "Сжатый кулак, большой палец прижат сбоку." },
    { letter: "B", image: "images/B.png", description: "Прямая ладонь, пальцы вместе, большой палец прижат." },
    { letter: "C", image: "images/C.png", description: "Рука изогнута в форме буквы C." },
    { letter: "D", image: "images/D.png", description: "Указательный палец вверх, остальные пальцы согнуты, большой палец касается среднего." },
    { letter: "E", image: "images/E.png", description: "Пальцы согнуты к ладони, большой палец прижат сверху." },
    { letter: "F", image: "images/F.png", description: "Круг из большого и указательного пальцев, остальные пальцы вверх." },
    { letter: "G", image: "images/G.png", description: "Указательный палец вперед, большой параллельно ему." },
    { letter: "H", image: "images/H.png", description: "Указательный и средний пальцы вытянуты вперед, остальные согнуты." },
    { letter: "I", image: "images/I.png", description: "Мизинец вверх, остальные пальцы сжаты." },
    { letter: "J", image: "images/J.png", description: "Мизинцем рисуется буква J в воздухе." },
    { letter: "K", image: "images/K.png", description: "Указательный и средний пальцы вверх, большой касается среднего." },
    { letter: "L", image: "images/L.png", description: "Указательный палец вверх, большой в сторону под прямым углом." },
    { letter: "M", image: "images/M.png", description: "Большой палец под тремя пальцами." },
    { letter: "N", image: "images/N.png", description: "Большой палец под двумя пальцами." },
    { letter: "O", image: "images/O.png", description: "Пальцы собраны в форму буквы O." },
    { letter: "P", image: "images/P.png", description: "Буква K, наклоненная вниз." },
    { letter: "Q", image: "images/Q.png", description: "Большой и указательный пальцы направлены вниз." },
    { letter: "R", image: "images/R.png", description: "Указательный и средний пальцы перекрещены." },
    { letter: "S", image: "images/S.png", description: "Сжатый кулак, большой палец поверх пальцев." },
    { letter: "T", image: "images/T.png", description: "Большой палец между указательным и средним пальцами." },
    { letter: "U", image: "images/U.png", description: "Указательный и средний пальцы сжаты вместе, направлены вверх." },
    { letter: "V", image: "images/V.png", description: "Указательный и средний пальцы вверх, образуют V." },
    { letter: "W", image: "images/W.png", description: "Три пальца вверх, образуют W." },
    { letter: "X", image: "images/X.png", description: "Согнутый указательный палец." },
    { letter: "Y", image: "images/Y.png", description: "Большой и мизинец вытянуты." },
    { letter: "Z", image: "images/Z.png", description: "Указательным пальцем рисуется буква Z в воздухе." }
];
